In [1]:
import numpy as np

In [83]:
arr = np.array([
         [[4,1,3], [7,1,6], [6,1,5]],
         [[1,1,9], [2,1,4], [5,1,6]],
         [[9,1,2], [3,1,4], [8,1,3]],
         [[6,7,2], [2,4,1], [7,3,4]]
         ])

print(arr.ndim)

3


In [44]:
arr[0][0, 0]

4

In [96]:
position_1 = [[i, j] for i in range(3) for j in range(3)]
print(position_1)

position_2 = [[i, j+3] for i in range(3) for j in range(3)]
print(position_2)

position_3 = [[i, j+6] for i in range(3) for j in range(3)]
print(position_3)

position_4 = [[i+3, j] for i in range(3) for j in range(3)]
print(position_4)

positions = position_1 + position_2 + position_3 + position_4
print(positions)

[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]
[[0, 3], [0, 4], [0, 5], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5]]
[[0, 6], [0, 7], [0, 8], [1, 6], [1, 7], [1, 8], [2, 6], [2, 7], [2, 8]]
[[3, 0], [3, 1], [3, 2], [4, 0], [4, 1], [4, 2], [5, 0], [5, 1], [5, 2]]
[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2], [0, 3], [0, 4], [0, 5], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [0, 6], [0, 7], [0, 8], [1, 6], [1, 7], [1, 8], [2, 6], [2, 7], [2, 8], [3, 0], [3, 1], [3, 2], [4, 0], [4, 1], [4, 2], [5, 0], [5, 1], [5, 2]]


In [62]:
it = np.nditer(arr, flags=['multi_index'])

for x in it:
    print("%d <%s>" % (x, it.multi_index), end=' ')

4 <(0, 0, 0)> 1 <(0, 0, 1)> 3 <(0, 0, 2)> 7 <(0, 1, 0)> 1 <(0, 1, 1)> 6 <(0, 1, 2)> 6 <(0, 2, 0)> 1 <(0, 2, 1)> 5 <(0, 2, 2)> 1 <(1, 0, 0)> 1 <(1, 0, 1)> 9 <(1, 0, 2)> 2 <(1, 1, 0)> 1 <(1, 1, 1)> 4 <(1, 1, 2)> 5 <(1, 2, 0)> 1 <(1, 2, 1)> 6 <(1, 2, 2)> 9 <(2, 0, 0)> 1 <(2, 0, 1)> 2 <(2, 0, 2)> 3 <(2, 1, 0)> 1 <(2, 1, 1)> 4 <(2, 1, 2)> 8 <(2, 2, 0)> 1 <(2, 2, 1)> 3 <(2, 2, 2)> 6 <(3, 0, 0)> 7 <(3, 0, 1)> 2 <(3, 0, 2)> 2 <(3, 1, 0)> 4 <(3, 1, 1)> 1 <(3, 1, 2)> 7 <(3, 2, 0)> 3 <(3, 2, 1)> 4 <(3, 2, 2)> 

In [76]:
it = np.nditer(arr)

for position, val in zip(positions, it):
    print(f"position: {position} has value {val}")


position: [0, 0] has value 4
position: [0, 1] has value 1
position: [0, 2] has value 3
position: [0, 3] has value 7
position: [0, 4] has value 1
position: [0, 5] has value 6
position: [0, 6] has value 6
position: [0, 7] has value 1
position: [0, 8] has value 5
position: [1, 0] has value 1
position: [1, 1] has value 1
position: [1, 2] has value 9
position: [1, 3] has value 2
position: [1, 4] has value 1
position: [1, 5] has value 4
position: [1, 6] has value 5
position: [1, 7] has value 1
position: [1, 8] has value 6
position: [2, 0] has value 9
position: [2, 1] has value 1
position: [2, 2] has value 2
position: [2, 3] has value 3
position: [2, 4] has value 1
position: [2, 5] has value 4
position: [2, 6] has value 8
position: [2, 7] has value 1
position: [2, 8] has value 3
position: [3, 0] has value 6
position: [3, 1] has value 7
position: [3, 2] has value 2
position: [3, 3] has value 2
position: [3, 4] has value 4
position: [3, 5] has value 1
position: [3, 6] has value 7
position: [3, 

In [87]:
for dim in range(arr.ndim+1):
    print(f"dimension : {dim}")
    it = np.nditer(arr[dim,...])
    print(arr[dim,...])
    for position, val in zip(positions, it):
        print(f"position: {position} has value {val}")

dimension : 0
[[4 1 3]
 [7 1 6]
 [6 1 5]]
position: [0, 0] has value 4
position: [0, 1] has value 1
position: [0, 2] has value 3
position: [0, 3] has value 7
position: [0, 4] has value 1
position: [0, 5] has value 6
position: [0, 6] has value 6
position: [0, 7] has value 1
position: [0, 8] has value 5
dimension : 1
[[1 1 9]
 [2 1 4]
 [5 1 6]]
position: [0, 0] has value 1
position: [0, 1] has value 1
position: [0, 2] has value 9
position: [0, 3] has value 2
position: [0, 4] has value 1
position: [0, 5] has value 4
position: [0, 6] has value 5
position: [0, 7] has value 1
position: [0, 8] has value 6
dimension : 2
[[9 1 2]
 [3 1 4]
 [8 1 3]]
position: [0, 0] has value 9
position: [0, 1] has value 1
position: [0, 2] has value 2
position: [0, 3] has value 3
position: [0, 4] has value 1
position: [0, 5] has value 4
position: [0, 6] has value 8
position: [0, 7] has value 1
position: [0, 8] has value 3
dimension : 3
[[6 7 2]
 [2 4 1]
 [7 3 4]]
position: [0, 0] has value 6
position: [0, 1] has

In [67]:
it = np.nditer(arr, flags=['multi_index'])

for position, val in zip(positions, it):
    print(f"position: {position} has value {val}")



position: [0, 0] has value 4
position: [0, 1] has value 1
position: [0, 2] has value 3
position: [0, 3] has value 7
position: [0, 4] has value 1
position: [0, 5] has value 6
position: [0, 6] has value 6
position: [0, 7] has value 1
position: [0, 8] has value 5
position: [1, 0] has value 1
position: [1, 1] has value 1
position: [1, 2] has value 9
position: [1, 3] has value 2
position: [1, 4] has value 1
position: [1, 5] has value 4
position: [1, 6] has value 5
position: [1, 7] has value 1
position: [1, 8] has value 6
position: [2, 0] has value 9
position: [2, 1] has value 1
position: [2, 2] has value 2
position: [2, 3] has value 3
position: [2, 4] has value 1
position: [2, 5] has value 4
position: [2, 6] has value 8
position: [2, 7] has value 1
position: [2, 8] has value 3
position: [3, 0] has value 6
position: [3, 1] has value 7
position: [3, 2] has value 2
position: [3, 3] has value 2
position: [3, 4] has value 4
position: [3, 5] has value 1
position: [3, 6] has value 7
position: [3, 

In [69]:
len(positions)

81